# Generated by scripts/update-ytui.sh — do not edit by hand.
class Ytui < Formula
  desc "Audio-first YouTube client for the terminal, light on RAM"
  homepage "https://github.com/OPS-NC/YTui"

  on_macos do
    on_arm do
      url "https://github.com/OPS-NC/YTui/releases/download/v0.2/ytui-macos-arm64"
      sha256 "ba035ff5543a3402d4d9a20dae7ba508f2493e39e816ee0ce5f06f3de9f39f88"
    end
    on_intel do
      url "https://github.com/OPS-NC/YTui/releases/download/v0.2/ytui-macos-x86_64"
      sha256 "0f9b9a604ff230e2bbd83d45093271fb47e88d0f1618ac7640ba75f015a77d09"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/OPS-NC/YTui/releases/download/v0.2/ytui-linux-aarch64"
      sha256 "74128cd81768e30d7eb2a9308094a5e7a236b0fba04be8eb13fff2a439f73c4a"
    end
    on_intel do
      url "https://github.com/OPS-NC/YTui/releases/download/v0.2/ytui-linux-x86_64"
      sha256 "c1bf3787e951a0cf4516aa7eff259efd0de40bfa6b8da17fae701396099046e5"
    end
  end

  def install
    bin.install Dir["ytui-*"].first => "ytui"
  end

  def caveats
    <<~EOS
      ffmpeg and a JS engine are embedded. yt-dlp is downloaded on first
      launch into ~/.local/share/ytui and kept up to date by ytui itself;
      set YTUI_YTDLP=yt-dlp to use Homebrew's yt-dlp instead.
      The video clip needs a truecolor terminal (Ghostty, Kitty, WezTerm, iTerm2).
    EOS
  end

  test do
    assert_predicate bin/"ytui", :executable?
  end
end
