# Generated by scripts/update-ytui.sh — do not edit by hand.
class Ytui < Formula
  desc "Audio-first YouTube client for the terminal, light on RAM"
  homepage "https://github.com/OPS-NC/YTui"
  version "0.1"

  on_macos do
    on_arm do
      url "https://github.com/OPS-NC/YTui/releases/download/v0.1/ytui-macos-arm64"
      sha256 "3555140645dee897adf8665b65c2183a80bf0e1dd6e8b738086761681c867766"
    end
    on_intel do
      url "https://github.com/OPS-NC/YTui/releases/download/v0.1/ytui-macos-x86_64"
      sha256 "94e2a8fb2b9d7eb31a85792a0906f4336dbe6570171250e043c60b6d5d93cd21"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/OPS-NC/YTui/releases/download/v0.1/ytui-linux-aarch64"
      sha256 "5a898b04e0f307ac0d3af26bbf9ca61fb4cb6c37b006fd593e5ebecf3177a448"
    end
    on_intel do
      url "https://github.com/OPS-NC/YTui/releases/download/v0.1/ytui-linux-x86_64"
      sha256 "a24c33a97175d6df191f3643cfbdeecdfb500340d93fdd0a4ca14eebfb19f123"
    end
  end

  def install
    bin.install Dir["ytui-*"].first => "ytui"
  end

  def caveats
    <<~EOS
      ffmpeg and a JS engine are embedded. yt-dlp is downloaded on first
      launch into ~/.local/share/ytui and kept up to date by ytui itself;
      set YTUI_YTDLP=yt-dlp to use Homebrew's yt-dlp instead.
      The video clip needs a truecolor terminal (Ghostty, Kitty, WezTerm, iTerm2).
    EOS
  end

  test do
    assert_predicate bin/"ytui", :executable?
  end
end
