#!/usr/bin/env bash
# Writes the Homebrew formula for a release from its SHA256SUMS.
#
#   scripts/update-ytui.sh v0.1 SHA256SUMS Formula/ytui.rb
#
# Run by .github/workflows/update-ytui.yml against the latest OPS-NC/YTui
# release. The formula installs the prebuilt standalone binaries (ffmpeg
# and qjs embedded, yt-dlp managed by ytui).
set -euo pipefail

TAG=${1:?usage: $0 <tag> <SHA256SUMS> <formula.rb>}
SUMS=${2:?}
OUT=${3:?}
VERSION=${TAG#v}
BASE="https://github.com/OPS-NC/YTui/releases/download/$TAG"

sum() {
    local hash
    hash=$(awk -v f="$1" '$2 == f || $2 == "*"f { print $1 }' "$SUMS")
    [ -n "$hash" ] || { echo "$1 absent de $SUMS" >&2; exit 1; }
    echo "$hash"
}

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<RUBY
# Generated by scripts/update-ytui.sh — do not edit by hand.
class Ytui < Formula
  desc "Audio-first YouTube client for the terminal, light on RAM"
  homepage "https://github.com/OPS-NC/YTui"
  version "$VERSION"

  on_macos do
    on_arm do
      url "$BASE/ytui-macos-arm64"
      sha256 "$(sum ytui-macos-arm64)"
    end
    on_intel do
      url "$BASE/ytui-macos-x86_64"
      sha256 "$(sum ytui-macos-x86_64)"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/ytui-linux-aarch64"
      sha256 "$(sum ytui-linux-aarch64)"
    end
    on_intel do
      url "$BASE/ytui-linux-x86_64"
      sha256 "$(sum ytui-linux-x86_64)"
    end
  end

  def install
    bin.install Dir["ytui-*"].first => "ytui"
  end

  def caveats
    <<~EOS
      ffmpeg and a JS engine are embedded. yt-dlp is downloaded on first
      launch into ~/.local/share/ytui and kept up to date by ytui itself;
      set YTUI_YTDLP=yt-dlp to use Homebrew's yt-dlp instead.
      The video clip needs a truecolor terminal (Ghostty, Kitty, WezTerm, iTerm2).
    EOS
  end

  test do
    assert_predicate bin/"ytui", :executable?
  end
end
RUBY
echo "$OUT → ytui $VERSION"
